require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ConnectionsController do

  # This should return the minimal set of attributes required to create a valid
  # Connection. As you add validations to Connection, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all connections as @connections" do
      connection = Connection.create! valid_attributes
      get :index
      assigns(:connections).should eq([connection])
    end
  end

  describe "GET show" do
    it "assigns the requested connection as @connection" do
      connection = Connection.create! valid_attributes
      get :show, :id => connection.id.to_s
      assigns(:connection).should eq(connection)
    end
  end

  describe "GET new" do
    it "assigns a new connection as @connection" do
      get :new
      assigns(:connection).should be_a_new(Connection)
    end
  end

  describe "GET edit" do
    it "assigns the requested connection as @connection" do
      connection = Connection.create! valid_attributes
      get :edit, :id => connection.id.to_s
      assigns(:connection).should eq(connection)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Connection" do
        expect {
          post :create, :connection => valid_attributes
        }.to change(Connection, :count).by(1)
      end

      it "assigns a newly created connection as @connection" do
        post :create, :connection => valid_attributes
        assigns(:connection).should be_a(Connection)
        assigns(:connection).should be_persisted
      end

      it "redirects to the created connection" do
        post :create, :connection => valid_attributes
        response.should redirect_to(Connection.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved connection as @connection" do
        # Trigger the behavior that occurs when invalid params are submitted
        Connection.any_instance.stub(:save).and_return(false)
        post :create, :connection => {}
        assigns(:connection).should be_a_new(Connection)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Connection.any_instance.stub(:save).and_return(false)
        post :create, :connection => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested connection" do
        connection = Connection.create! valid_attributes
        # Assuming there are no other connections in the database, this
        # specifies that the Connection created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Connection.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => connection.id, :connection => {'these' => 'params'}
      end

      it "assigns the requested connection as @connection" do
        connection = Connection.create! valid_attributes
        put :update, :id => connection.id, :connection => valid_attributes
        assigns(:connection).should eq(connection)
      end

      it "redirects to the connection" do
        connection = Connection.create! valid_attributes
        put :update, :id => connection.id, :connection => valid_attributes
        response.should redirect_to(connection)
      end
    end

    describe "with invalid params" do
      it "assigns the connection as @connection" do
        connection = Connection.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Connection.any_instance.stub(:save).and_return(false)
        put :update, :id => connection.id.to_s, :connection => {}
        assigns(:connection).should eq(connection)
      end

      it "re-renders the 'edit' template" do
        connection = Connection.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Connection.any_instance.stub(:save).and_return(false)
        put :update, :id => connection.id.to_s, :connection => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested connection" do
      connection = Connection.create! valid_attributes
      expect {
        delete :destroy, :id => connection.id.to_s
      }.to change(Connection, :count).by(-1)
    end

    it "redirects to the connections list" do
      connection = Connection.create! valid_attributes
      delete :destroy, :id => connection.id.to_s
      response.should redirect_to(connections_url)
    end
  end

end
