require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EmailListItemsController do

  # This should return the minimal set of attributes required to create a valid
  # EmailListItem. As you add validations to EmailListItem, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all email_list_items as @email_list_items" do
      email_list_item = EmailListItem.create! valid_attributes
      get :index
      assigns(:email_list_items).should eq([email_list_item])
    end
  end

  describe "GET show" do
    it "assigns the requested email_list_item as @email_list_item" do
      email_list_item = EmailListItem.create! valid_attributes
      get :show, :id => email_list_item.id.to_s
      assigns(:email_list_item).should eq(email_list_item)
    end
  end

  describe "GET new" do
    it "assigns a new email_list_item as @email_list_item" do
      get :new
      assigns(:email_list_item).should be_a_new(EmailListItem)
    end
  end

  describe "GET edit" do
    it "assigns the requested email_list_item as @email_list_item" do
      email_list_item = EmailListItem.create! valid_attributes
      get :edit, :id => email_list_item.id.to_s
      assigns(:email_list_item).should eq(email_list_item)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new EmailListItem" do
        expect {
          post :create, :email_list_item => valid_attributes
        }.to change(EmailListItem, :count).by(1)
      end

      it "assigns a newly created email_list_item as @email_list_item" do
        post :create, :email_list_item => valid_attributes
        assigns(:email_list_item).should be_a(EmailListItem)
        assigns(:email_list_item).should be_persisted
      end

      it "redirects to the created email_list_item" do
        post :create, :email_list_item => valid_attributes
        response.should redirect_to(EmailListItem.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved email_list_item as @email_list_item" do
        # Trigger the behavior that occurs when invalid params are submitted
        EmailListItem.any_instance.stub(:save).and_return(false)
        post :create, :email_list_item => {}
        assigns(:email_list_item).should be_a_new(EmailListItem)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        EmailListItem.any_instance.stub(:save).and_return(false)
        post :create, :email_list_item => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested email_list_item" do
        email_list_item = EmailListItem.create! valid_attributes
        # Assuming there are no other email_list_items in the database, this
        # specifies that the EmailListItem created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        EmailListItem.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => email_list_item.id, :email_list_item => {'these' => 'params'}
      end

      it "assigns the requested email_list_item as @email_list_item" do
        email_list_item = EmailListItem.create! valid_attributes
        put :update, :id => email_list_item.id, :email_list_item => valid_attributes
        assigns(:email_list_item).should eq(email_list_item)
      end

      it "redirects to the email_list_item" do
        email_list_item = EmailListItem.create! valid_attributes
        put :update, :id => email_list_item.id, :email_list_item => valid_attributes
        response.should redirect_to(email_list_item)
      end
    end

    describe "with invalid params" do
      it "assigns the email_list_item as @email_list_item" do
        email_list_item = EmailListItem.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        EmailListItem.any_instance.stub(:save).and_return(false)
        put :update, :id => email_list_item.id.to_s, :email_list_item => {}
        assigns(:email_list_item).should eq(email_list_item)
      end

      it "re-renders the 'edit' template" do
        email_list_item = EmailListItem.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        EmailListItem.any_instance.stub(:save).and_return(false)
        put :update, :id => email_list_item.id.to_s, :email_list_item => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested email_list_item" do
      email_list_item = EmailListItem.create! valid_attributes
      expect {
        delete :destroy, :id => email_list_item.id.to_s
      }.to change(EmailListItem, :count).by(-1)
    end

    it "redirects to the email_list_items list" do
      email_list_item = EmailListItem.create! valid_attributes
      delete :destroy, :id => email_list_item.id.to_s
      response.should redirect_to(email_list_items_url)
    end
  end

end
