require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe OperatingSystemsController do

  # This should return the minimal set of attributes required to create a valid
  # OperatingSystem. As you add validations to OperatingSystem, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all operating_systems as @operating_systems" do
      operating_system = OperatingSystem.create! valid_attributes
      get :index
      assigns(:operating_systems).should eq([operating_system])
    end
  end

  describe "GET show" do
    it "assigns the requested operating_system as @operating_system" do
      operating_system = OperatingSystem.create! valid_attributes
      get :show, :id => operating_system.id.to_s
      assigns(:operating_system).should eq(operating_system)
    end
  end

  describe "GET new" do
    it "assigns a new operating_system as @operating_system" do
      get :new
      assigns(:operating_system).should be_a_new(OperatingSystem)
    end
  end

  describe "GET edit" do
    it "assigns the requested operating_system as @operating_system" do
      operating_system = OperatingSystem.create! valid_attributes
      get :edit, :id => operating_system.id.to_s
      assigns(:operating_system).should eq(operating_system)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new OperatingSystem" do
        expect {
          post :create, :operating_system => valid_attributes
        }.to change(OperatingSystem, :count).by(1)
      end

      it "assigns a newly created operating_system as @operating_system" do
        post :create, :operating_system => valid_attributes
        assigns(:operating_system).should be_a(OperatingSystem)
        assigns(:operating_system).should be_persisted
      end

      it "redirects to the created operating_system" do
        post :create, :operating_system => valid_attributes
        response.should redirect_to(OperatingSystem.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved operating_system as @operating_system" do
        # Trigger the behavior that occurs when invalid params are submitted
        OperatingSystem.any_instance.stub(:save).and_return(false)
        post :create, :operating_system => {}
        assigns(:operating_system).should be_a_new(OperatingSystem)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        OperatingSystem.any_instance.stub(:save).and_return(false)
        post :create, :operating_system => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested operating_system" do
        operating_system = OperatingSystem.create! valid_attributes
        # Assuming there are no other operating_systems in the database, this
        # specifies that the OperatingSystem created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        OperatingSystem.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => operating_system.id, :operating_system => {'these' => 'params'}
      end

      it "assigns the requested operating_system as @operating_system" do
        operating_system = OperatingSystem.create! valid_attributes
        put :update, :id => operating_system.id, :operating_system => valid_attributes
        assigns(:operating_system).should eq(operating_system)
      end

      it "redirects to the operating_system" do
        operating_system = OperatingSystem.create! valid_attributes
        put :update, :id => operating_system.id, :operating_system => valid_attributes
        response.should redirect_to(operating_system)
      end
    end

    describe "with invalid params" do
      it "assigns the operating_system as @operating_system" do
        operating_system = OperatingSystem.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        OperatingSystem.any_instance.stub(:save).and_return(false)
        put :update, :id => operating_system.id.to_s, :operating_system => {}
        assigns(:operating_system).should eq(operating_system)
      end

      it "re-renders the 'edit' template" do
        operating_system = OperatingSystem.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        OperatingSystem.any_instance.stub(:save).and_return(false)
        put :update, :id => operating_system.id.to_s, :operating_system => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested operating_system" do
      operating_system = OperatingSystem.create! valid_attributes
      expect {
        delete :destroy, :id => operating_system.id.to_s
      }.to change(OperatingSystem, :count).by(-1)
    end

    it "redirects to the operating_systems list" do
      operating_system = OperatingSystem.create! valid_attributes
      delete :destroy, :id => operating_system.id.to_s
      response.should redirect_to(operating_systems_url)
    end
  end

end
