require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PerformanceTestsController do

  # This should return the minimal set of attributes required to create a valid
  # PerformanceTest. As you add validations to PerformanceTest, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all performance_tests as @performance_tests" do
      performance_test = PerformanceTest.create! valid_attributes
      get :index
      assigns(:performance_tests).should eq([performance_test])
    end
  end

  describe "GET show" do
    it "assigns the requested performance_test as @performance_test" do
      performance_test = PerformanceTest.create! valid_attributes
      get :show, :id => performance_test.id.to_s
      assigns(:performance_test).should eq(performance_test)
    end
  end

  describe "GET new" do
    it "assigns a new performance_test as @performance_test" do
      get :new
      assigns(:performance_test).should be_a_new(PerformanceTest)
    end
  end

  describe "GET edit" do
    it "assigns the requested performance_test as @performance_test" do
      performance_test = PerformanceTest.create! valid_attributes
      get :edit, :id => performance_test.id.to_s
      assigns(:performance_test).should eq(performance_test)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PerformanceTest" do
        expect {
          post :create, :performance_test => valid_attributes
        }.to change(PerformanceTest, :count).by(1)
      end

      it "assigns a newly created performance_test as @performance_test" do
        post :create, :performance_test => valid_attributes
        assigns(:performance_test).should be_a(PerformanceTest)
        assigns(:performance_test).should be_persisted
      end

      it "redirects to the created performance_test" do
        post :create, :performance_test => valid_attributes
        response.should redirect_to(PerformanceTest.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved performance_test as @performance_test" do
        # Trigger the behavior that occurs when invalid params are submitted
        PerformanceTest.any_instance.stub(:save).and_return(false)
        post :create, :performance_test => {}
        assigns(:performance_test).should be_a_new(PerformanceTest)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PerformanceTest.any_instance.stub(:save).and_return(false)
        post :create, :performance_test => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested performance_test" do
        performance_test = PerformanceTest.create! valid_attributes
        # Assuming there are no other performance_tests in the database, this
        # specifies that the PerformanceTest created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PerformanceTest.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => performance_test.id, :performance_test => {'these' => 'params'}
      end

      it "assigns the requested performance_test as @performance_test" do
        performance_test = PerformanceTest.create! valid_attributes
        put :update, :id => performance_test.id, :performance_test => valid_attributes
        assigns(:performance_test).should eq(performance_test)
      end

      it "redirects to the performance_test" do
        performance_test = PerformanceTest.create! valid_attributes
        put :update, :id => performance_test.id, :performance_test => valid_attributes
        response.should redirect_to(performance_test)
      end
    end

    describe "with invalid params" do
      it "assigns the performance_test as @performance_test" do
        performance_test = PerformanceTest.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PerformanceTest.any_instance.stub(:save).and_return(false)
        put :update, :id => performance_test.id.to_s, :performance_test => {}
        assigns(:performance_test).should eq(performance_test)
      end

      it "re-renders the 'edit' template" do
        performance_test = PerformanceTest.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PerformanceTest.any_instance.stub(:save).and_return(false)
        put :update, :id => performance_test.id.to_s, :performance_test => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested performance_test" do
      performance_test = PerformanceTest.create! valid_attributes
      expect {
        delete :destroy, :id => performance_test.id.to_s
      }.to change(PerformanceTest, :count).by(-1)
    end

    it "redirects to the performance_tests list" do
      performance_test = PerformanceTest.create! valid_attributes
      delete :destroy, :id => performance_test.id.to_s
      response.should redirect_to(performance_tests_url)
    end
  end

end
