require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PtestsController do

  # This should return the minimal set of attributes required to create a valid
  # Ptest. As you add validations to Ptest, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all ptests as @ptests" do
      ptest = Ptest.create! valid_attributes
      get :index
      assigns(:ptests).should eq([ptest])
    end
  end

  describe "GET show" do
    it "assigns the requested ptest as @ptest" do
      ptest = Ptest.create! valid_attributes
      get :show, :id => ptest.id.to_s
      assigns(:ptest).should eq(ptest)
    end
  end

  describe "GET new" do
    it "assigns a new ptest as @ptest" do
      get :new
      assigns(:ptest).should be_a_new(Ptest)
    end
  end

  describe "GET edit" do
    it "assigns the requested ptest as @ptest" do
      ptest = Ptest.create! valid_attributes
      get :edit, :id => ptest.id.to_s
      assigns(:ptest).should eq(ptest)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Ptest" do
        expect {
          post :create, :ptest => valid_attributes
        }.to change(Ptest, :count).by(1)
      end

      it "assigns a newly created ptest as @ptest" do
        post :create, :ptest => valid_attributes
        assigns(:ptest).should be_a(Ptest)
        assigns(:ptest).should be_persisted
      end

      it "redirects to the created ptest" do
        post :create, :ptest => valid_attributes
        response.should redirect_to(Ptest.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ptest as @ptest" do
        # Trigger the behavior that occurs when invalid params are submitted
        Ptest.any_instance.stub(:save).and_return(false)
        post :create, :ptest => {}
        assigns(:ptest).should be_a_new(Ptest)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Ptest.any_instance.stub(:save).and_return(false)
        post :create, :ptest => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ptest" do
        ptest = Ptest.create! valid_attributes
        # Assuming there are no other ptests in the database, this
        # specifies that the Ptest created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Ptest.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => ptest.id, :ptest => {'these' => 'params'}
      end

      it "assigns the requested ptest as @ptest" do
        ptest = Ptest.create! valid_attributes
        put :update, :id => ptest.id, :ptest => valid_attributes
        assigns(:ptest).should eq(ptest)
      end

      it "redirects to the ptest" do
        ptest = Ptest.create! valid_attributes
        put :update, :id => ptest.id, :ptest => valid_attributes
        response.should redirect_to(ptest)
      end
    end

    describe "with invalid params" do
      it "assigns the ptest as @ptest" do
        ptest = Ptest.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Ptest.any_instance.stub(:save).and_return(false)
        put :update, :id => ptest.id.to_s, :ptest => {}
        assigns(:ptest).should eq(ptest)
      end

      it "re-renders the 'edit' template" do
        ptest = Ptest.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Ptest.any_instance.stub(:save).and_return(false)
        put :update, :id => ptest.id.to_s, :ptest => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ptest" do
      ptest = Ptest.create! valid_attributes
      expect {
        delete :destroy, :id => ptest.id.to_s
      }.to change(Ptest, :count).by(-1)
    end

    it "redirects to the ptests list" do
      ptest = Ptest.create! valid_attributes
      delete :destroy, :id => ptest.id.to_s
      response.should redirect_to(ptests_url)
    end
  end

end
