require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TestSuitesController do

  # This should return the minimal set of attributes required to create a valid
  # TestSuite. As you add validations to TestSuite, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all test_suites as @test_suites" do
      test_suite = TestSuite.create! valid_attributes
      get :index
      assigns(:test_suites).should eq([test_suite])
    end
  end

  describe "GET show" do
    it "assigns the requested test_suite as @test_suite" do
      test_suite = TestSuite.create! valid_attributes
      get :show, :id => test_suite.id.to_s
      assigns(:test_suite).should eq(test_suite)
    end
  end

  describe "GET new" do
    it "assigns a new test_suite as @test_suite" do
      get :new
      assigns(:test_suite).should be_a_new(TestSuite)
    end
  end

  describe "GET edit" do
    it "assigns the requested test_suite as @test_suite" do
      test_suite = TestSuite.create! valid_attributes
      get :edit, :id => test_suite.id.to_s
      assigns(:test_suite).should eq(test_suite)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TestSuite" do
        expect {
          post :create, :test_suite => valid_attributes
        }.to change(TestSuite, :count).by(1)
      end

      it "assigns a newly created test_suite as @test_suite" do
        post :create, :test_suite => valid_attributes
        assigns(:test_suite).should be_a(TestSuite)
        assigns(:test_suite).should be_persisted
      end

      it "redirects to the created test_suite" do
        post :create, :test_suite => valid_attributes
        response.should redirect_to(TestSuite.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved test_suite as @test_suite" do
        # Trigger the behavior that occurs when invalid params are submitted
        TestSuite.any_instance.stub(:save).and_return(false)
        post :create, :test_suite => {}
        assigns(:test_suite).should be_a_new(TestSuite)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TestSuite.any_instance.stub(:save).and_return(false)
        post :create, :test_suite => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested test_suite" do
        test_suite = TestSuite.create! valid_attributes
        # Assuming there are no other test_suites in the database, this
        # specifies that the TestSuite created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TestSuite.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => test_suite.id, :test_suite => {'these' => 'params'}
      end

      it "assigns the requested test_suite as @test_suite" do
        test_suite = TestSuite.create! valid_attributes
        put :update, :id => test_suite.id, :test_suite => valid_attributes
        assigns(:test_suite).should eq(test_suite)
      end

      it "redirects to the test_suite" do
        test_suite = TestSuite.create! valid_attributes
        put :update, :id => test_suite.id, :test_suite => valid_attributes
        response.should redirect_to(test_suite)
      end
    end

    describe "with invalid params" do
      it "assigns the test_suite as @test_suite" do
        test_suite = TestSuite.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TestSuite.any_instance.stub(:save).and_return(false)
        put :update, :id => test_suite.id.to_s, :test_suite => {}
        assigns(:test_suite).should eq(test_suite)
      end

      it "re-renders the 'edit' template" do
        test_suite = TestSuite.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TestSuite.any_instance.stub(:save).and_return(false)
        put :update, :id => test_suite.id.to_s, :test_suite => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested test_suite" do
      test_suite = TestSuite.create! valid_attributes
      expect {
        delete :destroy, :id => test_suite.id.to_s
      }.to change(TestSuite, :count).by(-1)
    end

    it "redirects to the test_suites list" do
      test_suite = TestSuite.create! valid_attributes
      delete :destroy, :id => test_suite.id.to_s
      response.should redirect_to(test_suites_url)
    end
  end

end
